// Copyright (c) Microsoft Corporation
// Licensed under the MIT License.

//go:build ignore

// genlayout generates static layout information and
// a decoding method for all the table structs defined
// in the tables.go file of the working directory.
//
// The necessary information is taken using the following rules:
//
// - All structs in tables.go annotated with `// @table=$code` will be mapped to a WinMD table
// - The table code is taken from the struct doc line starting with `// @table=$code`
// - Index properties are treated as a table index
// - Index properties must have the comment `@ref=$table`, where $table is the name of the referenced table
// - CodedIndex properties are treated as a table coded index
// - CodedIndex properties use their single type argument as the coded tag family
// - String properties are treated as a String heap index
// - BlobIndex properties are treated as a Blob heap index
// - GUIDIndex properties are treated as a GUID heap index
//
// genlayout will panic if any of the previous rules are not met.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/types"
	"io"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	// parse
	pkg := parsePackage()
	file := findTableFile(pkg)
	tables := parseTables(pkg, file)

	// write
	w := new(bytes.Buffer)
	writePrelude(w)
	writeTablesStruct(w, tables)
	writeTableValues(w, tables)
	writeTableWidth(w, tables)
	writeTableEncoding(w, tables)

	src := formatSource(w.Bytes())
	err := os.WriteFile("zlayout.go", src, 0644)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
}

func formatSource(d []byte) []byte {
	src, err := format.Source(d)
	if err != nil {
		// Should never happen, but can arise when developing this code.
		// The user can compile the output to see the error.
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		log.Printf("warning: compile the package to analyze the error")
		err := os.WriteFile("zlayout.go.reject", d, 0644)
		if err != nil {
			log.Fatalf("writing rejected output: %s", err)
		}
		log.Fatal("refusing to overwrite zlayout.go with invalid generated output")
	}
	return src
}

func writePrelude(w io.Writer) {
	fmt.Fprintf(w, `
// Copyright (c) Microsoft Corporation
// Licensed under the MIT License.

// Code generated by "genlayout"; DO NOT EDIT.

package winmd

import "fmt"

`)
}

func writeTableValues(w io.Writer, tables []tableInfo) {
	// Sort tables by its code so the table
	// values are defined in a nice-looking increasing order.
	sorted := make([]struct {
		name  string
		value uint8
	}, len(tables))
	for i, t := range tables {
		sorted[i].name = t.tableName
		sorted[i].value = t.code
	}
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].value < sorted[j].value
	})

	fmt.Fprintf(w, "// Define table enum\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "type table uint8\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "const (\n")
	for _, t := range sorted {
		fmt.Fprintf(w, "\t%s table = %d\n", t.name, t.value)
	}
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "\ttableMax = %s + 1\n", sorted[len(sorted)-1].name)
	fmt.Fprintf(w, "\ttableNone = tableMax\n")
	fmt.Fprintf(w, ")\n")
	fmt.Fprintf(w, "\n")
}

func writeTableWidth(w io.Writer, tables []tableInfo) {
	fmt.Fprintf(w, "// Define table width\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "func (t table) width(la *layout) (uint8) {\n")
	fmt.Fprintf(w, "\tswitch t {\n")
	for _, t := range tables {
		fmt.Fprintf(w, "\tcase %s:\n", t.tableName)
		width := make([]string, len(t.fields))
		for i, c := range t.fields {
			switch c.columnType {
			case columnTypeCodedIndex:
				width[i] = "la.codedSizes[coded" + c.coded + "]"
			case columnTypeIndex, columnTypeSlice:
				width[i] = "la.simpleSizes[" + c.tableName + "]"
			case columnTypeString:
				width[i] = "la.stringSize"
			case columnTypeGUID:
				width[i] = "la.guidSize"
			case columnTypeBlob:
				width[i] = "la.blobSize"
			case columnTypeUint:
				width[i] = strconv.Itoa(c.size)
			}
		}
		fmt.Fprintf(w, "\t\treturn %s\n", strings.Join(width, " + "))
	}
	fmt.Fprintf(w, "\tdefault:\n")
	fmt.Fprintf(w, "\t\tpanic(fmt.Sprintf(\"table %%v not supported\", t))\n")
	fmt.Fprintf(w, "\t}\n")
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "\n")
}

func writeTablesStruct(w io.Writer, tables []tableInfo) {
	fmt.Fprintf(w, "// Define tables struct\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "// Tables provides access to the tables and records stored in the #~ stream\n")
	fmt.Fprintf(w, "// as defined in §II.24.2.6\n")
	fmt.Fprintf(w, "type Tables struct {\n")
	for _, t := range tables {
		if !t.exported {
			continue
		}
		fmt.Fprintf(w, "\t%s Table[%s]\n", t.name, t.name)
	}
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "func newTables(data []byte, hps *heaps, layout *layout) *Tables {\n")
	fmt.Fprintf(w, "\tvar t Tables\n")
	for _, t := range tables {
		if !t.exported {
			continue
		}
		fmt.Fprintf(w, "\tt.%s = newTable(%q, data, hps, layout, %s, decode%s)\n", t.name, t.name, t.tableName, t.name)
	}
	fmt.Fprintf(w, "\treturn &t\n")
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "\n")
}

func writeTableEncoding(w io.Writer, tables []tableInfo) {
	fmt.Fprintf(w, "// Define table decoding functions\n")
	fmt.Fprintf(w, "\n")
	for _, t := range tables {
		fmt.Fprintf(w, "func decode%s(r recordReader) (%s, error) {\n", t.name, t.name)
		fmt.Fprintf(w, "\tvar rec %s\n", t.name)
		for _, f := range t.fields {
			switch f.columnType {
			case columnTypeIndex:
				fmt.Fprintf(w, "\trec.%s = r.index(%s)\n", f.name, f.tableName)
			case columnTypeBlob:
				fmt.Fprintf(w, "\trec.%s = r.blob()\n", f.name)
			case columnTypeGUID:
				fmt.Fprintf(w, "\trec.%s = r.guid()\n", f.name)
			case columnTypeString:
				fmt.Fprintf(w, "\trec.%s = r.string()\n", f.name)
			case columnTypeUint:
				var fn string
				switch f.size {
				case 1:
					fn = "uint8"
				case 2:
					fn = "uint16"
				case 4:
					fn = "uint32"
				default:
					log.Fatalf("unsupported uint size %d", f.size)
				}
				if f.needsCast {
					fmt.Fprintf(w, "\trec.%s = %s(r.%s())\n", f.name, f.typeName, fn)
				} else {
					fmt.Fprintf(w, "\trec.%s = r.%s()\n", f.name, fn)
				}
			case columnTypeCodedIndex:
				fmt.Fprintf(w, "\trec.%s = readCoded[%s](&r.ecma335Reader)\n", f.name, f.coded)
			case columnTypeSlice:
				fmt.Fprintf(w, "\trec.%s = r.slice(%s, %s)\n", f.name, t.tableName, f.tableName)
			}
		}
		fmt.Fprintf(w, "\treturn rec, r.err\n")
		fmt.Fprintf(w, "}\n")
		fmt.Fprintf(w, "\n")
	}
}

const tablesFile = "tables.go"

type columnType string

const (
	columnTypeIndex      columnType = "columnTypeIndex"
	columnTypeUint       columnType = "columnTypeUint"
	columnTypeString     columnType = "columnTypeString"
	columnTypeGUID       columnType = "columnTypeGUID"
	columnTypeBlob       columnType = "columnTypeBlob"
	columnTypeCodedIndex columnType = "columnTypeCodedIndex"
	columnTypeSlice      columnType = "columnTypeSlice"
)

type tableInfo struct {
	name string
	// same as name but prefixed with "table" and with the first name letter upper-cased
	tableName string
	exported  bool
	code      uint8
	fields    []columnInfo
}

type columnInfo struct {
	name       string
	typeName   string
	size       int
	needsCast  bool
	columnType columnType
	tableName  string
	coded      string
}

func setUintColumn(col *columnInfo, tp types.Type) bool {
	basic, ok := tp.Underlying().(*types.Basic)
	if !ok {
		return false
	}

	var rawType types.Type
	switch basic.Kind() {
	case types.Uint8:
		col.size = 1
		rawType = types.Typ[types.Uint8]
	case types.Uint16:
		col.size = 2
		rawType = types.Typ[types.Uint16]
	case types.Uint32:
		col.size = 4
		rawType = types.Typ[types.Uint32]
	default:
		return false
	}

	col.columnType = columnTypeUint
	col.needsCast = !types.Identical(tp, rawType)
	return true
}

// parsePackage analyzes the single package constructed from the current directory.
func parsePackage() *packages.Package {
	cfg := &packages.Config{
		Mode:  packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax,
		Tests: false,
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		log.Fatal(err)
	}
	if len(pkgs) != 1 {
		log.Fatalf("error: %d packages found", len(pkgs))
	}
	return pkgs[0]
}

func findTableFile(pkg *packages.Package) *ast.File {
	for _, s := range pkg.Syntax {
		f := pkg.Fset.File(s.Pos())
		if f != nil && filepath.Base(f.Name()) == tablesFile {
			return s
		}
	}
	log.Fatalf("%q not found", tablesFile)
	return nil
}

func parseTables(pkg *packages.Package, file *ast.File) []tableInfo {
	var tables []tableInfo
	// traverse the file looking for ast.TypeSpec
	ast.Inspect(file, func(n ast.Node) bool {
		decl, ok := n.(*ast.GenDecl)
		if !ok || len(decl.Specs) != 1 {
			return true
		}
		if tableCode(decl) == nil {
			return false
		}
		spec, ok := decl.Specs[0].(*ast.TypeSpec)
		if !ok {
			// some specs do not define a type
			return false
		}
		if _, ok := pkg.TypesInfo.TypeOf(spec.Type).Underlying().(*types.Struct); !ok {
			log.Panicf("@table type %s must be a struct", spec.Name.Name)
		}
		info := parseTable(pkg, spec)
		info.code = *tableCode(decl)
		info.tableName = tableName(info.name)
		tables = append(tables, info)
		return false
	})

	// verify that there are exactly 38 tables
	const want = 38
	if got := len(tables); got != want {
		log.Fatalf("got %d tables, want %d", got, want)
	}

	// verify there are no duplicated codes
	codes := make(map[uint8]struct{}, len(tables))
	for _, t := range tables {
		if _, ok := codes[t.code]; ok {
			log.Fatalf("code %#x is duplicated", t.code)
		}
		codes[t.code] = struct{}{}
	}
	return tables
}

// parseTable parses a table from the given spec.
func parseTable(pkg *packages.Package, spec *ast.TypeSpec) (info tableInfo) {
	// this code does not do any effort to do check if the type-casted interfaces
	// will panic at runtime or not. If something panic it means that tables.go does
	// not met genlayout rules.
	t := pkg.TypesInfo.TypeOf(spec.Type).(*types.Struct)
	n := t.NumFields()
	info.name = spec.Name.Name
	info.exported = spec.Name.IsExported()
	info.fields = make([]columnInfo, 0, n)
	for i := 0; i < n; i++ {
		f := t.Field(i)
		var col columnInfo
		tp := f.Type()
		col.name = f.Name()
		switch tp := tp.(type) {
		case *types.Named:
			obj := tp.Obj()
			col.typeName = obj.Name()
			switch objName := obj.Name(); objName {
			case "Index":
				col.columnType = columnTypeIndex
				col.tableName = tableName(fieldComment(spec, i, objName, tp.String(), "@ref"))
			case "CodedIndex":
				col.columnType = columnTypeCodedIndex
				col.coded = codedTypeName(tp)
			case "Slice":
				col.columnType = columnTypeSlice
				col.tableName = tableName(fieldComment(spec, i, objName, tp.String(), "@ref"))
			case "String":
				col.columnType = columnTypeString
			default:
				if strings.HasPrefix(objName, "Sig") && strings.HasSuffix(objName, "Blob") {
					col.columnType = columnTypeBlob
				} else {
					setUintColumn(&col, tp)
				}
			}
		case *types.Basic:
			col.typeName = tp.Name()
			setUintColumn(&col, tp)
		case *types.Array:
			if tp.Len() == 16 {
				col.columnType = columnTypeGUID
			}
		case *types.Slice:
			col.columnType = columnTypeBlob
		}
		if col.columnType == "" {
			log.Panicf("unsupported type %s", tp.String())
		}
		info.fields = append(info.fields, col)
	}
	return
}

func codedTypeName(tp *types.Named) string {
	args := tp.TypeArgs()
	if args == nil || args.Len() != 1 {
		log.Panicf("CodedIndex %s requires exactly one type argument", tp.String())
	}
	arg := args.At(0)
	named, ok := arg.(*types.Named)
	if !ok {
		log.Panicf("CodedIndex %s type argument must be a named type", tp.String())
	}
	return named.Obj().Name()
}

func fieldComment(spec *ast.TypeSpec, i int, t, tp, marker string) (v string) {
	comment := spec.Type.(*ast.StructType).Fields.List[i].Comment
	if comment != nil && len(comment.List) == 1 {
		v = strings.TrimPrefix(comment.List[0].Text, "// "+marker+"=")
	}
	if v == "" {
		log.Panicf("%s %s requires %s comment", t, tp, marker)
	}
	return v
}

func tableCode(decl *ast.GenDecl) *uint8 {
	if decl.Doc == nil {
		return nil
	}
	for _, c := range decl.Doc.List {
		const tablePrefix = "// @table="
		if strings.HasPrefix(c.Text, tablePrefix) {
			code, err := strconv.ParseUint(c.Text[len(tablePrefix):], 0, 8)
			if err != nil {
				log.Panic(err)
			}
			v := uint8(code)
			return &v
		}
	}
	return nil
}

func tableName(s string) string {
	return "table" + strings.ToUpper(s[:1]) + s[1:]
}
