// Copyright (c) Microsoft Corporation
// Licensed under the MIT License.

// Code generated by "genlayout"; DO NOT EDIT.

package winmd

import "fmt"

// Define tables struct

// Tables provides access to the tables and records stored in the #~ stream
// as defined in §II.24.2.6
type Tables struct {
	Assembly               Table[Assembly]
	AssemblyRef            Table[AssemblyRef]
	ClassLayout            Table[ClassLayout]
	Constant               Table[Constant]
	CustomAttribute        Table[CustomAttribute]
	DeclSecurity           Table[DeclSecurity]
	EventMap               Table[EventMap]
	Event                  Table[Event]
	ExportedType           Table[ExportedType]
	Field                  Table[Field]
	FieldLayout            Table[FieldLayout]
	FieldMarshal           Table[FieldMarshal]
	FieldRVA               Table[FieldRVA]
	File                   Table[File]
	GenericParam           Table[GenericParam]
	GenericParamConstraint Table[GenericParamConstraint]
	ImplMap                Table[ImplMap]
	InterfaceImpl          Table[InterfaceImpl]
	ManifestResource       Table[ManifestResource]
	MemberRef              Table[MemberRef]
	MethodDef              Table[MethodDef]
	MethodImpl             Table[MethodImpl]
	MethodSemantics        Table[MethodSemantics]
	MethodSpec             Table[MethodSpec]
	Module                 Table[Module]
	ModuleRef              Table[ModuleRef]
	NestedClass            Table[NestedClass]
	Param                  Table[Param]
	Property               Table[Property]
	PropertyMap            Table[PropertyMap]
	StandAloneSig          Table[StandAloneSig]
	TypeDef                Table[TypeDef]
	TypeRef                Table[TypeRef]
	TypeSpec               Table[TypeSpec]
}

func newTables(data []byte, hps heaps, layout *layout) *Tables {
	var t Tables
	t.Assembly = newTable(data, hps, layout, tableAssembly, decodeAssembly)
	t.AssemblyRef = newTable(data, hps, layout, tableAssemblyRef, decodeAssemblyRef)
	t.ClassLayout = newTable(data, hps, layout, tableClassLayout, decodeClassLayout)
	t.Constant = newTable(data, hps, layout, tableConstant, decodeConstant)
	t.CustomAttribute = newTable(data, hps, layout, tableCustomAttribute, decodeCustomAttribute)
	t.DeclSecurity = newTable(data, hps, layout, tableDeclSecurity, decodeDeclSecurity)
	t.EventMap = newTable(data, hps, layout, tableEventMap, decodeEventMap)
	t.Event = newTable(data, hps, layout, tableEvent, decodeEvent)
	t.ExportedType = newTable(data, hps, layout, tableExportedType, decodeExportedType)
	t.Field = newTable(data, hps, layout, tableField, decodeField)
	t.FieldLayout = newTable(data, hps, layout, tableFieldLayout, decodeFieldLayout)
	t.FieldMarshal = newTable(data, hps, layout, tableFieldMarshal, decodeFieldMarshal)
	t.FieldRVA = newTable(data, hps, layout, tableFieldRVA, decodeFieldRVA)
	t.File = newTable(data, hps, layout, tableFile, decodeFile)
	t.GenericParam = newTable(data, hps, layout, tableGenericParam, decodeGenericParam)
	t.GenericParamConstraint = newTable(data, hps, layout, tableGenericParamConstraint, decodeGenericParamConstraint)
	t.ImplMap = newTable(data, hps, layout, tableImplMap, decodeImplMap)
	t.InterfaceImpl = newTable(data, hps, layout, tableInterfaceImpl, decodeInterfaceImpl)
	t.ManifestResource = newTable(data, hps, layout, tableManifestResource, decodeManifestResource)
	t.MemberRef = newTable(data, hps, layout, tableMemberRef, decodeMemberRef)
	t.MethodDef = newTable(data, hps, layout, tableMethodDef, decodeMethodDef)
	t.MethodImpl = newTable(data, hps, layout, tableMethodImpl, decodeMethodImpl)
	t.MethodSemantics = newTable(data, hps, layout, tableMethodSemantics, decodeMethodSemantics)
	t.MethodSpec = newTable(data, hps, layout, tableMethodSpec, decodeMethodSpec)
	t.Module = newTable(data, hps, layout, tableModule, decodeModule)
	t.ModuleRef = newTable(data, hps, layout, tableModuleRef, decodeModuleRef)
	t.NestedClass = newTable(data, hps, layout, tableNestedClass, decodeNestedClass)
	t.Param = newTable(data, hps, layout, tableParam, decodeParam)
	t.Property = newTable(data, hps, layout, tableProperty, decodeProperty)
	t.PropertyMap = newTable(data, hps, layout, tablePropertyMap, decodePropertyMap)
	t.StandAloneSig = newTable(data, hps, layout, tableStandAloneSig, decodeStandAloneSig)
	t.TypeDef = newTable(data, hps, layout, tableTypeDef, decodeTypeDef)
	t.TypeRef = newTable(data, hps, layout, tableTypeRef, decodeTypeRef)
	t.TypeSpec = newTable(data, hps, layout, tableTypeSpec, decodeTypeSpec)
	return &t
}

// Define table enum

type table uint8

const (
	tableModule                 table = 0
	tableTypeRef                table = 1
	tableTypeDef                table = 2
	tableField                  table = 4
	tableMethodDef              table = 6
	tableParam                  table = 8
	tableInterfaceImpl          table = 9
	tableMemberRef              table = 10
	tableConstant               table = 11
	tableCustomAttribute        table = 12
	tableFieldMarshal           table = 13
	tableDeclSecurity           table = 14
	tableClassLayout            table = 15
	tableFieldLayout            table = 16
	tableStandAloneSig          table = 17
	tableEventMap               table = 18
	tableEvent                  table = 20
	tablePropertyMap            table = 21
	tableProperty               table = 23
	tableMethodSemantics        table = 24
	tableMethodImpl             table = 25
	tableModuleRef              table = 26
	tableTypeSpec               table = 27
	tableImplMap                table = 28
	tableFieldRVA               table = 29
	tableAssembly               table = 32
	tableAssemblyProcessor      table = 33
	tableAssemblyOS             table = 34
	tableAssemblyRef            table = 35
	tableAssemblyRefProcessor   table = 36
	tableAssemblyRefOS          table = 37
	tableFile                   table = 38
	tableExportedType           table = 39
	tableManifestResource       table = 40
	tableNestedClass            table = 41
	tableGenericParam           table = 42
	tableMethodSpec             table = 43
	tableGenericParamConstraint table = 44

	tableMax  = tableGenericParamConstraint + 1
	tableNone = tableMax
)

// Define table width

func (t table) width(la *layout) uint8 {
	switch t {
	case tableAssembly:
		return 4 + 2 + 2 + 2 + 2 + 4 + la.blobSize + la.stringSize + la.stringSize
	case tableAssemblyOS:
		return 4 + 4 + 4
	case tableAssemblyProcessor:
		return 4
	case tableAssemblyRef:
		return 2 + 2 + 2 + 2 + 4 + la.blobSize + la.stringSize + la.stringSize + la.blobSize
	case tableAssemblyRefOS:
		return 4 + 4 + 4 + la.simpleSizes[tableAssemblyRef]
	case tableAssemblyRefProcessor:
		return 4 + la.simpleSizes[tableAssemblyRef]
	case tableClassLayout:
		return 2 + 4 + la.simpleSizes[tableTypeDef]
	case tableConstant:
		return 1 + 1 + la.codedSizes[codedHasConstant] + la.blobSize
	case tableCustomAttribute:
		return la.codedSizes[codedHasCustomAttribute] + la.codedSizes[codedCustomAttributeType] + la.blobSize
	case tableDeclSecurity:
		return 2 + la.codedSizes[codedHasDeclSecurity] + la.blobSize
	case tableEventMap:
		return la.simpleSizes[tableTypeDef] + la.simpleSizes[tableEvent]
	case tableEvent:
		return 2 + la.stringSize + la.codedSizes[codedTypeDefOrRef]
	case tableExportedType:
		return 4 + 4 + la.stringSize + la.stringSize + la.codedSizes[codedImplementation]
	case tableField:
		return 2 + la.stringSize + la.blobSize
	case tableFieldLayout:
		return 4 + la.simpleSizes[tableField]
	case tableFieldMarshal:
		return la.codedSizes[codedHasFieldMarshal] + la.blobSize
	case tableFieldRVA:
		return 4 + la.simpleSizes[tableField]
	case tableFile:
		return 2 + la.stringSize + la.blobSize
	case tableGenericParam:
		return 2 + 2 + la.codedSizes[codedTypeOrMethodDef] + la.stringSize
	case tableGenericParamConstraint:
		return la.simpleSizes[tableGenericParam] + la.codedSizes[codedTypeDefOrRef]
	case tableImplMap:
		return 2 + la.codedSizes[codedMemberForwarded] + la.stringSize + la.simpleSizes[tableModuleRef]
	case tableInterfaceImpl:
		return la.simpleSizes[tableTypeDef] + la.codedSizes[codedTypeDefOrRef]
	case tableManifestResource:
		return 4 + 4 + la.stringSize + la.codedSizes[codedImplementation]
	case tableMemberRef:
		return la.codedSizes[codedMemberRefParent] + la.stringSize + la.blobSize
	case tableMethodDef:
		return 4 + 2 + 2 + la.stringSize + la.blobSize + la.simpleSizes[tableParam]
	case tableMethodImpl:
		return la.simpleSizes[tableTypeDef] + la.codedSizes[codedMethodDefOrRef] + la.codedSizes[codedMethodDefOrRef]
	case tableMethodSemantics:
		return 2 + la.simpleSizes[tableMethodDef] + la.codedSizes[codedHasSemantics]
	case tableMethodSpec:
		return la.codedSizes[codedMethodDefOrRef] + la.blobSize
	case tableModule:
		return 2 + la.stringSize + la.guidSize + la.guidSize + la.guidSize
	case tableModuleRef:
		return la.stringSize
	case tableNestedClass:
		return la.simpleSizes[tableTypeDef] + la.simpleSizes[tableTypeDef]
	case tableParam:
		return 2 + 2 + la.stringSize
	case tableProperty:
		return 2 + la.stringSize + la.blobSize
	case tablePropertyMap:
		return la.simpleSizes[tableTypeDef] + la.simpleSizes[tableProperty]
	case tableStandAloneSig:
		return la.blobSize
	case tableTypeDef:
		return 4 + la.stringSize + la.stringSize + la.codedSizes[codedTypeDefOrRef] + la.simpleSizes[tableField] + la.simpleSizes[tableMethodDef]
	case tableTypeRef:
		return la.codedSizes[codedResolutionScope] + la.stringSize + la.stringSize
	case tableTypeSpec:
		return la.blobSize
	default:
		panic(fmt.Sprintf("table %v not supported", t))
	}
}

// Define table decoding functions

func decodeAssembly(rec *Assembly, r recordReader) error {
	rec.HashAlgID = AssemblyHashAlgorithm(r.uint32())
	rec.MajorVersion = r.uint16()
	rec.MinorVersion = r.uint16()
	rec.BuildNumber = r.uint16()
	rec.RevisionNumber = r.uint16()
	rec.Flags = AssemblyFlags(r.uint32())
	rec.PublicKey = r.blob()
	rec.Name = r.string()
	rec.Culture = r.string()
	return r.err
}

func decodeassemblyOS(rec *assemblyOS, r recordReader) error {
	rec.OSPlatformID = r.uint32()
	rec.OSMajorVersion = r.uint32()
	rec.OSMinorVersion = r.uint32()
	return r.err
}

func decodeassemblyProcessor(rec *assemblyProcessor, r recordReader) error {
	rec.Processor = r.uint32()
	return r.err
}

func decodeAssemblyRef(rec *AssemblyRef, r recordReader) error {
	rec.MajorVersion = r.uint16()
	rec.MinorVersion = r.uint16()
	rec.BuildNumber = r.uint16()
	rec.RevisionNumber = r.uint16()
	rec.Flags = AssemblyFlags(r.uint32())
	rec.PublicKeyOrToken = r.blob()
	rec.Name = r.string()
	rec.Culture = r.string()
	rec.HashValue = r.blob()
	return r.err
}

func decodeassemblyRefOS(rec *assemblyRefOS, r recordReader) error {
	rec.OSPlatformID = r.uint32()
	rec.OSMajorVersion = r.uint32()
	rec.OSMinorVersion = r.uint32()
	rec.AssemblyRef = r.index(tableAssemblyRef)
	return r.err
}

func decodeassemblyRefProcessor(rec *assemblyRefProcessor, r recordReader) error {
	rec.Processor = r.uint32()
	rec.AssemblyRef = r.index(tableAssemblyRef)
	return r.err
}

func decodeClassLayout(rec *ClassLayout, r recordReader) error {
	rec.PackingSize = r.uint16()
	rec.ClassSize = r.uint32()
	rec.Parent = r.index(tableTypeDef)
	return r.err
}

func decodeConstant(rec *Constant, r recordReader) error {
	rec.Type = ElementType(r.uint8())
	rec.Padding = r.uint8()
	rec.Parent = readCoded[HasConstant](&r.ecma335Reader)
	rec.Value = r.blob()
	return r.err
}

func decodeCustomAttribute(rec *CustomAttribute, r recordReader) error {
	rec.Parent = readCoded[HasCustomAttribute](&r.ecma335Reader)
	rec.Type = readCoded[CustomAttributeType](&r.ecma335Reader)
	rec.Value = r.blob()
	return r.err
}

func decodeDeclSecurity(rec *DeclSecurity, r recordReader) error {
	rec.Action = r.uint16()
	rec.Parent = readCoded[HasDeclSecurity](&r.ecma335Reader)
	rec.PermissionSet = r.blob()
	return r.err
}

func decodeEventMap(rec *EventMap, r recordReader) error {
	rec.Parent = r.index(tableTypeDef)
	rec.EventList = r.slice(tableEventMap, tableEvent)
	return r.err
}

func decodeEvent(rec *Event, r recordReader) error {
	rec.EventFlags = EventAttributes(r.uint16())
	rec.Name = r.string()
	rec.EventType = readCoded[TypeDefOrRef](&r.ecma335Reader)
	return r.err
}

func decodeExportedType(rec *ExportedType, r recordReader) error {
	rec.Flags = TypeAttributes(r.uint32())
	rec.TypeDefID = r.uint32()
	rec.Name = r.string()
	rec.Namespace = r.string()
	rec.Implementation = readCoded[Implementation](&r.ecma335Reader)
	return r.err
}

func decodeField(rec *Field, r recordReader) error {
	rec.Flags = FieldAttributes(r.uint16())
	rec.Name = r.string()
	rec.Signature = r.blob()
	return r.err
}

func decodeFieldLayout(rec *FieldLayout, r recordReader) error {
	rec.Offset = r.uint32()
	rec.Field = r.index(tableField)
	return r.err
}

func decodeFieldMarshal(rec *FieldMarshal, r recordReader) error {
	rec.Parent = readCoded[HasFieldMarshal](&r.ecma335Reader)
	rec.NativeType = r.blob()
	return r.err
}

func decodeFieldRVA(rec *FieldRVA, r recordReader) error {
	rec.RVA = r.uint32()
	rec.Field = r.index(tableField)
	return r.err
}

func decodeFile(rec *File, r recordReader) error {
	rec.Flags = FileAttributes(r.uint16())
	rec.Name = r.string()
	rec.HashValue = r.blob()
	return r.err
}

func decodeGenericParam(rec *GenericParam, r recordReader) error {
	rec.Number = r.uint16()
	rec.Flags = GenericParamAttributes(r.uint16())
	rec.Owner = readCoded[TypeOrMethodDef](&r.ecma335Reader)
	rec.Name = r.string()
	return r.err
}

func decodeGenericParamConstraint(rec *GenericParamConstraint, r recordReader) error {
	rec.Owner = r.index(tableGenericParam)
	rec.Constraint = readCoded[TypeDefOrRef](&r.ecma335Reader)
	return r.err
}

func decodeImplMap(rec *ImplMap, r recordReader) error {
	rec.MappingFlags = PInvokeAttributes(r.uint16())
	rec.MemberForwarded = readCoded[MemberForwarded](&r.ecma335Reader)
	rec.ImportName = r.string()
	rec.ImportScope = r.index(tableModuleRef)
	return r.err
}

func decodeInterfaceImpl(rec *InterfaceImpl, r recordReader) error {
	rec.Class = r.index(tableTypeDef)
	rec.Interface = readCoded[TypeDefOrRef](&r.ecma335Reader)
	return r.err
}

func decodeManifestResource(rec *ManifestResource, r recordReader) error {
	rec.Offset = r.uint32()
	rec.Flags = ManifestResourceAttributes(r.uint32())
	rec.Name = r.string()
	rec.Implementation = readCoded[Implementation](&r.ecma335Reader)
	return r.err
}

func decodeMemberRef(rec *MemberRef, r recordReader) error {
	rec.Class = readCoded[MemberRefParent](&r.ecma335Reader)
	rec.Name = r.string()
	rec.Signature = r.blob()
	return r.err
}

func decodeMethodDef(rec *MethodDef, r recordReader) error {
	rec.RVA = r.uint32()
	rec.ImplFlags = MethodImplAttributes(r.uint16())
	rec.Flags = MethodAttributes(r.uint16())
	rec.Name = r.string()
	rec.Signature = r.blob()
	rec.ParamList = r.slice(tableMethodDef, tableParam)
	return r.err
}

func decodeMethodImpl(rec *MethodImpl, r recordReader) error {
	rec.Class = r.index(tableTypeDef)
	rec.MethodBody = readCoded[MethodDefOrRef](&r.ecma335Reader)
	rec.MethodDeclaration = readCoded[MethodDefOrRef](&r.ecma335Reader)
	return r.err
}

func decodeMethodSemantics(rec *MethodSemantics, r recordReader) error {
	rec.Semantics = MethodSemanticsAttributes(r.uint16())
	rec.Method = r.index(tableMethodDef)
	rec.Association = readCoded[HasSemantics](&r.ecma335Reader)
	return r.err
}

func decodeMethodSpec(rec *MethodSpec, r recordReader) error {
	rec.Method = readCoded[MethodDefOrRef](&r.ecma335Reader)
	rec.Instantiation = r.blob()
	return r.err
}

func decodeModule(rec *Module, r recordReader) error {
	rec.Generation = r.uint16()
	rec.Name = r.string()
	rec.Mvid = r.guid()
	rec.EncID = r.guid()
	rec.EncBaseID = r.guid()
	return r.err
}

func decodeModuleRef(rec *ModuleRef, r recordReader) error {
	rec.Name = r.string()
	return r.err
}

func decodeNestedClass(rec *NestedClass, r recordReader) error {
	rec.NestedClass = r.index(tableTypeDef)
	rec.EnclosingClass = r.index(tableTypeDef)
	return r.err
}

func decodeParam(rec *Param, r recordReader) error {
	rec.Flags = ParamAttributes(r.uint16())
	rec.Sequence = r.uint16()
	rec.Name = r.string()
	return r.err
}

func decodeProperty(rec *Property, r recordReader) error {
	rec.Flags = PropertyAttributes(r.uint16())
	rec.Name = r.string()
	rec.Type = r.blob()
	return r.err
}

func decodePropertyMap(rec *PropertyMap, r recordReader) error {
	rec.Parent = r.index(tableTypeDef)
	rec.PropertyList = r.slice(tablePropertyMap, tableProperty)
	return r.err
}

func decodeStandAloneSig(rec *StandAloneSig, r recordReader) error {
	rec.Signature = r.blob()
	return r.err
}

func decodeTypeDef(rec *TypeDef, r recordReader) error {
	rec.Flags = TypeAttributes(r.uint32())
	rec.Name = r.string()
	rec.Namespace = r.string()
	rec.Extends = readCoded[TypeDefOrRef](&r.ecma335Reader)
	rec.FieldList = r.slice(tableTypeDef, tableField)
	rec.MethodList = r.slice(tableTypeDef, tableMethodDef)
	return r.err
}

func decodeTypeRef(rec *TypeRef, r recordReader) error {
	rec.ResolutionScope = readCoded[ResolutionScope](&r.ecma335Reader)
	rec.Name = r.string()
	rec.Namespace = r.string()
	return r.err
}

func decodeTypeSpec(rec *TypeSpec, r recordReader) error {
	rec.Signature = r.blob()
	return r.err
}
