// Code generated by "stringer -type=AssemblyHashAlgorithm -trimprefix AssemblyHash_Algorithm"; DO NOT EDIT.

package flags

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AssemblyHash_AlgorithmNone-0]
	_ = x[AssemblyHash_AlgorithmMD5-32771]
	_ = x[AssemblyHash_AlgorithmSHA1-32772]
}

const (
	_AssemblyHashAlgorithm_name_0 = "None"
	_AssemblyHashAlgorithm_name_1 = "MD5SHA1"
)

var (
	_AssemblyHashAlgorithm_index_1 = [...]uint8{0, 3, 7}
)

func (i AssemblyHashAlgorithm) String() string {
	switch {
	case i == 0:
		return _AssemblyHashAlgorithm_name_0
	case 32771 <= i && i <= 32772:
		i -= 32771
		return _AssemblyHashAlgorithm_name_1[_AssemblyHashAlgorithm_index_1[i]:_AssemblyHashAlgorithm_index_1[i+1]]
	default:
		return "AssemblyHashAlgorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
