// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// genlayout generates table layout information and decoders from the schema
// source files in the working directory. It parses Go syntax, without loading
// or type-checking the winmd package or reading previously generated files.
//
// Tables are non-generic struct definitions annotated with // @table=<code>.
// Index and Slice fields require // @ref=<table name>, above or after the field.
// Supported column types are uint8/uint16/uint32 (including byte, named integer
// types, and aliases), String, Index, Slice, CodedIndex[T], byte slices, and
// byte arrays with literal length 16. Coded tag names come from CodedTag's
// union terms. Other Go type shapes are rejected rather than guessed.
package main

import (
	"bytes"
	"cmp"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"slices"
	"strconv"
	"strings"
)

func main() {
	tables, err := readTables(".")
	if err != nil {
		log.Fatal(err)
	}
	src := formatSource(generate(tables))
	if err := os.WriteFile("zlayout.go", src, 0644); err != nil {
		log.Fatalf("writing output: %s", err)
	}
}

func generate(tables []tableInfo) []byte {
	w := new(bytes.Buffer)
	writePrelude(w)
	writeTablesStruct(w, tables)
	writeTableValues(w, tables)
	writeTableWidth(w, tables)
	writeTableEncoding(w, tables)
	return w.Bytes()
}

func formatSource(d []byte) []byte {
	src, err := format.Source(d)
	if err != nil {
		// Keep invalid output for debugging without replacing the existing layout.
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		if err := os.WriteFile("zlayout.go.reject", d, 0644); err != nil {
			log.Fatalf("writing rejected output: %s", err)
		}
		log.Fatal("refusing to overwrite zlayout.go with invalid generated output")
	}
	return src
}

func writePrelude(w io.Writer) {
	fmt.Fprintf(w, `
// Copyright (c) Microsoft Corporation
// Licensed under the MIT License.

// Code generated by "genlayout"; DO NOT EDIT.

package winmd

import "fmt"

`)
}

func writeTableValues(w io.Writer, tables []tableInfo) {
	// Sort tables by code so the values are defined in increasing order.
	type tableValue struct {
		name  string
		value uint8
	}
	sorted := make([]tableValue, len(tables))
	for i, t := range tables {
		sorted[i].name = t.tableName
		sorted[i].value = t.code
	}
	slices.SortFunc(sorted, func(a, b tableValue) int {
		return cmp.Compare(a.value, b.value)
	})

	fmt.Fprintf(w, "// Define table enum\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "type table uint8\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "const (\n")
	for _, t := range sorted {
		fmt.Fprintf(w, "\t%s table = %d\n", t.name, t.value)
	}
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "\ttableMax = %s + 1\n", sorted[len(sorted)-1].name)
	fmt.Fprintf(w, "\ttableNone = tableMax\n")
	fmt.Fprintf(w, ")\n")
	fmt.Fprintf(w, "\n")
}

func writeTableWidth(w io.Writer, tables []tableInfo) {
	fmt.Fprintf(w, "// Define table width\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "func (t table) width(la *layout) (uint8) {\n")
	fmt.Fprintf(w, "\tswitch t {\n")
	for _, t := range tables {
		fmt.Fprintf(w, "\tcase %s:\n", t.tableName)
		width := make([]string, len(t.fields))
		for i, c := range t.fields {
			switch c.columnType {
			case columnTypeCodedIndex:
				width[i] = "la.codedSizes[coded" + c.coded + "]"
			case columnTypeIndex, columnTypeSlice:
				width[i] = "la.simpleSizes[" + c.tableName + "]"
			case columnTypeString:
				width[i] = "la.stringSize"
			case columnTypeGUID:
				width[i] = "la.guidSize"
			case columnTypeBlob:
				width[i] = "la.blobSize"
			case columnTypeUint:
				width[i] = strconv.Itoa(c.size)
			}
		}
		fmt.Fprintf(w, "\t\treturn %s\n", strings.Join(width, " + "))
	}
	fmt.Fprintf(w, "\tdefault:\n")
	fmt.Fprintf(w, "\t\tpanic(fmt.Sprintf(\"table %%v not supported\", t))\n")
	fmt.Fprintf(w, "\t}\n")
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "\n")
}

func writeTablesStruct(w io.Writer, tables []tableInfo) {
	fmt.Fprintf(w, "// Define tables struct\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "// Tables provides access to the tables and records stored in the #~ stream\n")
	fmt.Fprintf(w, "// as defined in §II.24.2.6\n")
	fmt.Fprintf(w, "type Tables struct {\n")
	for _, t := range tables {
		if !t.exported {
			continue
		}
		fmt.Fprintf(w, "\t%s Table[%s]\n", t.name, t.name)
	}
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "func newTables(data []byte, hps *heaps, layout *layout) *Tables {\n")
	fmt.Fprintf(w, "\tvar t Tables\n")
	for _, t := range tables {
		if !t.exported {
			continue
		}
		fmt.Fprintf(w, "\tt.%s = newTable(%q, data, hps, layout, %s, decode%s)\n", t.name, t.name, t.tableName, t.name)
	}
	fmt.Fprintf(w, "\treturn &t\n")
	fmt.Fprintf(w, "}\n")
	fmt.Fprintf(w, "\n")
}

func writeTableEncoding(w io.Writer, tables []tableInfo) {
	fmt.Fprintf(w, "// Define table decoding functions\n")
	fmt.Fprintf(w, "\n")
	for _, t := range tables {
		fmt.Fprintf(w, "func decode%s(r recordReader) (%s, error) {\n", t.name, t.name)
		fmt.Fprintf(w, "\tvar rec %s\n", t.name)
		for _, f := range t.fields {
			switch f.columnType {
			case columnTypeIndex:
				fmt.Fprintf(w, "\trec.%s = r.index(%s)\n", f.name, f.tableName)
			case columnTypeBlob:
				fmt.Fprintf(w, "\trec.%s = r.blob()\n", f.name)
			case columnTypeGUID:
				fmt.Fprintf(w, "\trec.%s = r.guid()\n", f.name)
			case columnTypeString:
				fmt.Fprintf(w, "\trec.%s = r.string()\n", f.name)
			case columnTypeUint:
				var fn string
				switch f.size {
				case 1:
					fn = "uint8"
				case 2:
					fn = "uint16"
				case 4:
					fn = "uint32"
				default:
					log.Fatalf("unsupported uint size %d", f.size)
				}
				if f.needsCast {
					fmt.Fprintf(w, "\trec.%s = %s(r.%s())\n", f.name, f.typeName, fn)
				} else {
					fmt.Fprintf(w, "\trec.%s = r.%s()\n", f.name, fn)
				}
			case columnTypeCodedIndex:
				fmt.Fprintf(w, "\trec.%s = readCoded[%s](&r.ecma335Reader)\n", f.name, f.coded)
			case columnTypeSlice:
				fmt.Fprintf(w, "\trec.%s = r.slice(%s, %s)\n", f.name, t.tableName, f.tableName)
			}
		}
		fmt.Fprintf(w, "\treturn rec, r.err\n")
		fmt.Fprintf(w, "}\n")
		fmt.Fprintf(w, "\n")
	}
}
