on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.25.x, 1.26.x]
        venv: [windows-2022, windows-2025, windows-11-arm]
    runs-on: ${{ matrix.venv }}
    steps:
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Run Test - Build
      env:
        RACE_FLAG: ${{ runner.arch != 'ARM64' && '-race' || '' }}
      run: go test -v $RACE_FLAG ./...

