on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.25.x, 1.26.x]
        venv: [windows-2022, windows-2025, windows-11-arm]
    runs-on: ${{ matrix.venv }}
    steps:
    - name: Install Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Run Test - Build
      env:
        RACE_FLAG: ${{ runner.arch != 'ARM64' && '-race' || '' }}
      run: go test -v $RACE_FLAG ./...

